sudo: true
language: rust
cache: cargo
rust:
  - nightly
  - nightly-2016-11-20
  - beta
  - stable
  - 1.11.0
matrix:
    allow_failures:
        - rust: nightly
before_script:
  - |
    pip install git+git://github.com/kbknapp/travis-cargo.git --user &&
    export PATH=$HOME/.local/bin:$PATH
script:
  - |
    travis-cargo test -- --verbose --no-default-features &&
    travis-cargo --skip nightly test -- --verbose --features "yaml unstable" &&
    travis-cargo --only nightly test -- --verbose --features "yaml unstable nightly"
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
